/**
....................................................................................................................................................................................
....................................................................................................................................................................................
....................................................................................................................................................................................
....................................................................................................................................................................................
....................................................................................................................................................................................
....................................................................................................................................................................................
....................................................................................................................................................................................
....................................................................................................................................................................................
.................... .. . .. .. .......  . .   .... .......  ...  .. . ...... .. . . .... .... . . .... . .   .   ...   . .. .... . . .  ... .. . .   .... ..   .   ................
...................  .. . . .....   .  .  . .  ..  .. .      .  . . . . .  .... .. .   ...    .  . . . . ,.      . . . .......... . . . . . .. .. . .  .  . ...  .    ..............
.................. NMMMM+ . IMMMM? .MMMN: .~ZMMMN=.+MMMMMD= .   +MMMMM..DMMM=.+MMM$... NMMMMMMMOMMMNMMMM~MMMMMM,  .MMMM ..ZMMMMM =MMMMMM?.,$MMMMM?MMMM:..=MMMMM:.$MMM,..............
............. .. ~=  .. .M:N.. .. MZ=. 7M.D   ... MM.  ..  M. ..O... .8:7. ~M.M   O.  .I ..  . M ..7=.  M  . . Z  O . .~.:I..  .=M=  ... 88O.. ..M=  .M,O..    ,ND   I..............
..............  ,M . M=..$M:  8D. ,M=. 7M N . D ..+M. .+. .?,..:I     M=7. ~M.M   8. ..7 .    .M ..7= . M  .. .I..O . .~.:: . . NM=  ~I  .M8.  ..M~ ..M,M. .O . MM   ~..............
............... ~M.  M7. =M ..MM ..M=. 7M,I  .M...=M. .O  .=:. =. .I .MI7. ~M M. .O...  ~M ..8.M...7= . M  ..D,...O    ~.Z.. I  MM= .7M.  M8   M,~= . M:M.. DI7IDM .:~..............
................~M  .MOII$M   MM ..M=. 7M,7 ..M   ~M . . . N, .N  .M..7M7. ~M.M.  8.....~M ..O.M.   .   M  .   ,..O ...~,M .~N .8M=   ...888. . .M= . M.I,.  .$I~M  ~:..............
................~M ..DZMMDM   MM ..M=. 7M,7...M   ~M ..+.  Z.. M..~M  .M7. ~M.M.  8.....~M ..O.M.   . . M  . . :..O . .=+M. 7M. =M= .~I ..M8.  . M+...M..+M . ..NM. 7,..............
................~M . M7 .~M   MM ..M=. 7M,7  .M   ~M ..8   =,. M..~7   87. ~M.M.  8.....~M ..O.M.  I=   M  . M~...O ...~8O..+7  .M= .7M  .M8   M=:=...M=D7II=. .MM..7...............
.............. .:M. .M7. IM. .MM  .M~..IMMZ.. M  .~M. .O. .~: ,7 ..  ..+7  ~MMM.. OM?.  =M   O.M   7=. .M .  MM=..O .  MM~       M= .IM . M8  .MMM=...MMM...M=. M8OOM ..............
.................?.      M=$. .. .8N=.. ..M..     MM . 8.. =:.~: .7M  . 7. ...M  . .M:. ~M. .O M   7= . M..  . M,.O  . .:   8M  .M~. . .. MO.. ..7=.....8.......MM. ~:..............
................. :MI77M?. .MN77DM .MMMMMM7IMOI$M8.IMMMDMMMM..,MMM8~MMMMMMMMMMOMMMMMI... IMMM,.+MMMMMMMM=MMMMMM+..,MMMMMMMMMI~MMMMMMMMMMMI:8MMMMMMMMMMMMD?M777M7.+MMM...............
................... ,,,... .. ,,....+++++++?..,.... ... .  . .   .    .. ..  . . . . ...=+..... .     ..  ... .  .  ..... .....M. ..........~+++++++++++=..:,,  . .. ...............
..................  .....    ...  . +++++++=+=....  . ....  ......... ........... .....,++......   . . ...... ..  .  .....,~..:$  .......=+++++++++++++.........  . . ..............
.................. . .   ....  ... ..=+++++++++=...... . . ..  .  ..  ..... . .. ..  ..++=:... . .. .. ..   .. . .....:++===..+?. ...,,+++++++++++++++.......   .. . ...............
.....................................~++++++++++++,..... ............+=+............ .=+++= .......................=++++++....I:...:+++++++++++++++++...............................
......................................+++++++++++++~................:+++:..........  .+++++.......................+++++++,....8..:+++++++++++++++++=,...............................
......................................++++++++++++++++,.............=++++~...........~+++++....................,++++++++......M~?++++++++++++++++=+.................................
......................................:+++++++++++++++++,...........++++++=.........:++++++~. ...............:+++++++++.....=+M++++++++++++++++++=..................................
.......................................++++++++++++++++++++.........+++++++=,.......++++++++...............,=+++++++++:.,~++++M+++++++++++++++++~...................................
.......................................+++++++++++++++++++++~.......+++++++++,......++++++++..............++++++++++++.=++++++8+++++++++++++++++....................................
.......................................:++++++++++++++++++++++=.....++++++++++=....,++++++++............=++++++++++++++++++++IO+++++++++++++++:.....................................
........................................~+++++++++++++++++++++++:...++++++++++++:..~++++++++~........~+++=+++++++++++++++++++$7++++++++++++++:......................................
  .......................................++++++++++++++++++++++++=..++++++++++++++.+++++++++=.....,=+++++++++++++++++++++++++N++++++++++++++,.......................................
.. ......................................:+++++++++++++++++++++++++=++++++++++++++++++++++++=..,++++++++++++++++++++++++++++7M+++++++++++++:........................................
   .......................................++++++++++++++++++++++++++++++++++++++++?$DDDD7?+++,~+++++++++++++++++++++++++++++$M++++++++++++,.........................................
..........................................~++++++++++++++++++++++++++++++++?IMMZI:::::::::OMI++=++++++++++++7MMMMI++++++++++OM+++++++++++:..........................................
...........................................+++++++++++++++++++++++++++++7MD=::::::::::::::::IMZ++++++++++?MM.,....MI++++++++NZ++++++++++~...........................................
...............~++=,.......................:+++++++++++++++++++++++++++++78MO::,::::::::::::::M?+=++++?+?M=........ND+++++++M7+++++++++~............................................
................:++++:......................:=++++++++++++++++++++++++++++++IM?::::::::::::,:=OZ8MMMMMMNMM..... Z..$M+=+++++MI+++++++++,............................................
..................:++++++:,..................+++++++++++++++++++++++++++++++++?MN,,:::ZNMMI:,.~..,..... NN .  .....=N++++++?8++++++++=..............................................
....................=++++++++,...............,+++++++++++++++++++++++++++++++++++$MM?~.,..........  . . DM~.. . ...MO++++++I$+++++++=...............................................
.....................,:+++++++++: ............=+++++++++++++++++++++++++++=+++?ZM=........ ...... , .,..:MMM.. ...M?NZ+++++$7+++++++,...............................................
.......................~++++++++++,...........,+++++++++++++++++++++++++=+?+=+$M?. .............,ODDDDO~..MMM8?7DM,. M+=+++O?++++++=................................................
.........................==++++++++++,.........~++++++++++++++++++++++++IMI..,$NI. ........ 7MM,D  ,... M. ..:,.  .  .M++++M=++++++.................................................
..... ....,.. ............,++++++++++++=~.......+++++++++++++++++++++++?N... ..,?$,  ... 7MI, :,8O?M8MMMMM.. .  .......N+++M++++++:.. ..............................................
.... ..$M7,............... .++++++++++++++++=,...=+++++++++++++++++++++N..7. . . M. ..$MO, :,MMMMMMMMMMMMMMI. . .......7$++M+++++,..................................................
....  .+MIMM.................++++++++++=+++++++=,:+++++++++++++++++++++N..,..  ..M .NO$,,..MMMMMMMMMMMMMMMMM.  .........M?+N++++=...................................................
.....,:ZO+::NN..... ..........++++++++++++++++++++++++++++++++++++++++=?8... .  +ZO$,.,MMMMMMMMMMMMMMMMMMMMMO...........DNI8?=++,...............................................,:..
:,...:N~:~~:::ZM:.. ...........,++++++++++++++++++++++++++++++++++++++++7M~.. ?M7MD..ZMMMMMMMMMMMMMMMMMMMMMMM.. ..... ..7M7Z+++=...........................................,=+++=,..
M=8M$::~:::::~::NM... ..........,++++++++++++++++++++++++++++++++++++++++++ZM:..I? DMMMMMMMMMMMMMMMMMMMMMMMMMI. .........M8++++.......................................,=+++++++:....
?Z::~:~::::::::~~?M....  ........:++++++++++++++++++++++++++++++++++++++++++M...ID MMMMMMMMMMMMMMMMMMMMMMMMMMM....... ...ZM+=++............,::==...................:+++++++++:......
MM=::::::::::~::::~M=..............:++++++++++++++++++++++++++++++++++++++++O=...~MMMMMMMMMMMMMMMMMMMMMMMMMMMM .........,8M+++:....,~+++++++++:................~+++++++++++:........
O::~~:::::::::::::::IN...............~+++++++++++++++++++++++++++++++++++++++M .. ,IMMMMMMMMMMMMMMMMMMMMMMMMMM.......  .MMM++==+++++++++++++=...... .......:++++++++++++=...........
D~::::::::::::::::~:~OM ....,++++++++=++++++++++++++++++++++++++++++++++++++?M.... ...MMMMMMMMMMMMMMMMMMMMMMMM=........:D7M+++++++++++++++~,.. ........,~+++++++++++++=.............
M~::::::::::::::::~:~:M:. ....+++++++++++++++++++++++++++++++++++++++++++++++D+.. .  ..MMMMMMMMMMMMMMMMMMMMMMM=........,DIM++++++++++++++~...........:+++++++++++++++,..............
.M:~:::::::::::::::~::~M........~+++++++++++++++++++++++++++++++++++++++++++==M?.. .....:OMMMMMMMMMMMMMMMMMMMM= ......,?ZID+++++++++++++:........:++=+++++++++++++=,................
..N::::~::::::::::::::~IZ.........+++++++++++++++++++++++++++++++++++++++++++++MD .. . . .7MMMMMMMMMMMMMMMMMM== .......N7IIN+++++++++++,.....,=+++++++++++++++++,...................
..~Z~~~:::::::::::::::::M..........,+++++++++++++++++++++++++++++++++++++++++++7M:..  .  .:MMMMMMMMMMMMMMMMMM~+........NI7IM?++++++++~...,=+++++++++++++++++++......................
...DM:::::::::::::::::::M...........,+=++++++++++++++++++++++++++++++++++++++++++M:. .. . .MMMMMMMMMMMMMMMMM,.+.......NZ777Z$+++++++=..:=+++++++++++++++++++,.......................
. . .M:::::::::::~~~:+::M.............:+++++=++++++++++++++++++++++++++++++++++++$N........MMMMMMMMMMMMMMM:.7M+. .. .=Z77I77MI+++++~=+++++++++++++++=+++++..........................
 .. ..N?:::::::~:~:~~~~?................,+++++++++++++++++++++++++++++++++++++IMMI87...... M DMMMMMMMMMM8~..8 ,     .MII7777DM++++++++=++++++++++++++++:............................
.......MM8:::::~~D$MMOOM+.... ............+++++++++++++++++++++++++++++++++?8M+++++M:. ....:NO?. O+O$I.., MM:......+M77II7777N+++++++++++++++++++++++~..............................
...... ....,...,..+NOOOOD8,..  ............:+++++++++++++++++++++++++++++OMI=+?+++=+MD.. .....,~MMMMMMMMMZ, .. ....M87I7777I7$8++++++++++++++++++++,................................
....  .  ..........ZN88OONM. ........,~==+++++++++++++++++++++++++++++?IMZ++++++++++OM,.... .. . .      ..  . . ..IZ777777777IM+++++++++++++++++++,.................................
....................=M8OO8OM==++++++++++++++++++++++++++++++++++++++7MZ++++++++++++++?M~,................ .......,M7I777777777N+++++++++++++++++=...................................
.....................~ONOOOODZ?=+++++++++++++++++++++++++++++++++7MM+++++++++++++++++=+MMZ.... . .     . ..  .8MN77I7777777777$Z+++++++++++++++:....................................
....................=++7NOOOODN?+=+++++++++++++++++++++++++++=+8M+++++++++++++++++++++++MZDM7,......... . 7OMZ7I77777777777777IM+++++++++++++:......................................
......................,+7DOOOODM++=++++++++++++++++++++++++++NMI++++++++++++++++++++++++ND7IZMMMM8$$$$$$NMZ77777777777777777777M++++++++++++:........................... ...........
........................,?NDOOOONI++++++++++++++++++++++?+7M$+?+++++++++++++++++++++++++7M7I77777IIIIII7I77I7777777777777777777ZZ++++++++++.....................  ..................
.......,++++++++++~........$NOOOON8++++++++++++++++++++$N7?++++++++++++++++++++++++++++++?MI777II7777777I777777777777777777777I7M+++++++++++++++++++++++++++++++++++++==~::.........
........,+++++++++++++++=,,.,M8OO88M7++++++++++++=++ZND+++++++++++++++++++++++++++++++++++ZZ77777777777777777777777777777777777I8?++++++++++++++++++++++++++++++++++++++++++++==,...
.........:+++++++++++++++++=?7N8OZOOM??++++++=++++?MDI+++++++++++++++++++++++++++++++++++++MI777777777777777777777777777777777I7$O+++++++++++++++++++++++++++++++++++++++++++++++~..
..........:+++++++++++=++++++++8NOOOONZ+++++++++MM7+++++++++++++++++++++++++++++++++++++++?ZO77777777777777777777777777777777777IM$+++++++++++++++++++++++++++++++++++++++++++++++++
...........:++++++++++++++++++++IMOOO8DN+=+++OMI++++++++++++++++++++++++++++++++++++++++++++MI77777777777777777777777777777777777DM++++++++++++++++++++++++++++++++++++++++++++++=,,
............~+++++++++++++++++++++MNOOO8M$ZM8+++++++++++++++++++++++++++++++++++++++++++++++$Z777777777777777777777777777777777777M++++++++++++++++++++++++++++++++++++++++~,.......
.............~++++++++++++++++++++IDDOOO8MO+++++++++++++++++++++++++++++++++++++++++++++++++?M7II7I7777777777777777777777777777II78I+++++++++++++++++++++++++++++++++++=,...... ....
..............++++++++++++++++++++++$MMDOONZ+++++++++++++++++++++++++++++++++++++++++++++++++NNI7I7777777777777777777777777777777778++++++++++++++++++++++++++++++=,................
...............+++++++++++++++++++++?+MZOOO8MI++++++++++++++++++++++++++++++++++++++++++++++++DZ7I777777777777777777777777777777777M+++++++++++++++++++++++++=,..... ...............
...............,+++++++++++++++++++++++MNOO8ON8+++++++++++++++++++++++++++++++++++++++++++++++O$7777777777777777777777777777777777IM+++++++++++++++++++++~.... .....................
............. ..~+++++++++++++++++++++++ONO8OON7++++++++++++++++++++++++++++++++++++++++++++++O77777777777777777777777777777777777IM++++++++++++++++++:.............................
.................,+++++++++++++++++++++++IMO88OND+++++++++++++++++++++++++++++++++++++++++++++MI77I7777777777777777777777777777777IM++++++++++++++:... .............................
..................,++++++++++++++++++++++++MN8OO8M?++++++++++++++++++++++++++++++++++++++++++?MI77I7777777777777777777777777777777IM++++++++++=~....................................
....................+++++++++++++++++++++++=7MOOOODO+++++++++++++++++++++++++++++++++++++++++$M7I777777777777777777777777777777777IM+++++++=.... ....  . ............. ..  .........
....................:++++++++++++++++++++++++ZNOOOON$++=+++++++++++++++++++++++++++++++++++++NN7II77777777777777777777777777777777IM++++++++.......  .. ........  ..................
......................+++++++++++++++++++++++++MO8O8DM?++++++++++++++++++++++++++++++++++++=+MO77777777777777777777777777777777777IM+++++++++?,.,,~~,,:~,,,,..,,,,,,..,...,.,,.,,,..
.......................,++++++++++++++++++++++++MNOOOONZ++++++++++++++++++++++++++++++++++++?N777777777777777777777777777777777777IM+++++++??$+Z?.:+.~..I.==:I+, ~.=7=~?~.=I+ :,,=+:
........................,+++++++++++++++++++++=+++MOO8ODN+++++++++++++++++++++++++++++++++++$$777777777777777777777777777777777777IM+++++++?7:=$~=,I,:.~,.+I:?.~.+ +7. +::.?.:,=,I=:
.........................~++++++++++++++++++++++++IMO8OON8++++++++++++++++++++++++++++++++++87777777777777777777777777777777777777IM++++++++?7?I??+.,:,.,,,,,,,,,,,,,::,,,:.,,,,.,,.
*/

// COLOR ALL THE LABELS
$(function() {
	'use strict';

	$('input[placeholder],input[data-var]').colorBootsrap();
	$('input[placeholder],input[data-var]').on('input',function(){
		$(this).colorBootsrap();
	});
});

(function($){
	'use strict';

	// legalColors regex checks for starts with a valid CSS color prefix or is a legal named color value.
	// If you really wanted to, the regex could include stricter checks for valid CSS formats other than just checking the prefix.
	// lessColors are user configureable LESS variables in Twitter Bootstrap.  Some are not exposed on the customization page.
	var COLORS = {
			legalColors : /^[#|rgb|hsl|AliceBlue|AntiqueWhite|Aqua|Aquamarine|Azure|Beige|Bisque|Black|BlanchedAlmond|Blue|BlueViolet|Brown|BurlyWood|CadetBlue|Chartreuse|Chocolate|Coral|CornflowerBlue|Cornsilk|Crimson|Cyan|DarkBlue|DarkCyan|DarkGoldenRod|DarkGray|DarkGrey|DarkGreen|DarkKhaki|DarkMagenta|DarkOliveGreen|Darkorange|DarkOrchid|DarkRed|DarkSalmon|DarkSeaGreen|DarkSlateBlue|DarkSlateGray|DarkSlateGrey|DarkTurquoise|DarkViolet|DeepPink|DeepSkyBlue|DimGray|DimGrey|DodgerBlue|FireBrick|FloralWhite|ForestGreen|Fuchsia|Gainsboro|GhostWhite|Gold|GoldenRod|Gray|Grey|Green|GreenYellow|HoneyDew|HotPink|IndianRed |Indigo |Ivory|Khaki|Lavender|LavenderBlush|LawnGreen|LemonChiffon|LightBlue|LightCoral|LightCyan|LightGoldenRodYellow|LightGray|LightGrey|LightGreen|LightPink|LightSalmon|LightSeaGreen|LightSkyBlue|LightSlateGray|LightSlateGrey|LightSteelBlue|LightYellow|Lime|LimeGreen|Linen|Magenta|Maroon|MediumAquaMarine|MediumBlue|MediumOrchid|MediumPurple|MediumSeaGreen|MediumSlateBlue|MediumSpringGreen|MediumTurquoise|MediumVioletRed|MidnightBlue|MintCream|MistyRose|Moccasin|NavajoWhite|Navy|OldLace|Olive|OliveDrab|Orange|OrangeRed|Orchid|PaleGoldenRod|PaleGreen|PaleTurquoise|PaleVioletRed|PapayaWhip|PeachPuff|Peru|Pink|Plum|PowderBlue|Purple|Red|RosyBrown|RoyalBlue|SaddleBrown|Salmon|SandyBrown|SeaGreen|SeaShell|Sienna|Silver|SkyBlue|SlateBlue|SlateGray|SlateGrey|Snow|SpringGreen|SteelBlue|Tan|Teal|Thistle|Tomato|Turquoise|Violet|Wheat|White|WhiteSmoke|Yellow|YellowGreen]/i,
			lessColors : ['@blue','@green','@red','@yellow','@orange','@pink','@purple','@linkColor','@linkColorHover','@textColor','@black','@grayDarker','@grayDark','@gray','@grayLight','@grayLighter','@white','@heroUnitHeadingColor','@heroUnitLeadColor','@navbarBackground','@navbarBackgroundHighlight','@navbarText','@navbarBrandColor','@navbarLinkColorActive','@navbarLinkColorHover','@navbarLinkBackgroundActive','@navbarLinkBackgroundHover','@navbarSearchBackground','@navbarSearchBackgroundFocus','@navbarSearchBorder','@navbarSearchPlaceholderColor','@dropdownBackground','@dropdownBorder','@dropdownLinkColor','@dropdownLinkColorHover','@dropdownLinkBackgroundHover','@tableBackground','@tableBackgroundAccent','@tableBackgroundHover','@tableBorder','@placeholderText','@inputBackground','@inputBorder','@inputDisabledBackground','@formActionsBackground','@btnPrimaryBackground','@btnPrimaryBackgroundHighlight','@warningText','@warningBackground','@errorText','@errorBackground','@successText','@successBackground','@infoText','@infoBackground','@body-bg', '@code-color', '@code-bg', '@pre-color', '@pre-bg', '@pre-border-color', '@brand-primary', '@brand-success', '@brand-warning', '@brand-danger', '@brand-info', '@text-color', '@link-color', '@link-color-hover', '@component-active-bg', '@btn-default-color', '@btn-default-bg', '@btn-default-border', '@btn-success-color', '@btn-success-bg', '@btn-success-border', '@btn-primary-color', '@btn-primary-bg', '@btn-primary-border', '@btn-warning-color', '@btn-warning-bg', '@wbtn-warning-border', '@btn-info-color', '@btn-info-bg', '@btn-info-border', '@btn-danger-color', '@btn-danger-bg', '@btn-danger-border', '@btn-hover-color', '@state-success-text', '@state-success-bg', '@state-success-border', '@state-warning-text', '@state-warning-bg', '@state-warning-border', '@state-danger-text', '@state-danger-bg', '@state-danger-border', '@state-info-text', '@state-info-bg', '@state-info-border', '@alert-text', '@alert-bg', '@alert-border', '@alert-danger-text', '@alert-danger-bg', '@alert-danger-border', '@alert-success-text', '@alert-success-bg', '@alert-success-border', '@alert-info-text', '@alert-info-bg', '@alert-info-border', '@navbar-default-color', '@navbar-default-bg', '@navbar-inverse-color', '@navbar-inverse-bg', '@navbar-inverse-link-color', '@navbar-inverse-link-hover-color', '@navbar-inverse-link-hover-bg', '@navbar-default-link-color', '@navbar-default-link-hover-color', '@navbar-default-link-hover-bg', '@navbar-default-link-active-color', '@navbar-default-link-active-bg', '@navbar-default-link-disabled-color', '@navbar-default-link-disabled-bg', '@navbar-default-brand-color', '@navbar-default-brand-hover-color', '@navbar-default-brand-hover-bg', '@navbar-default-toggle-hover-bg', '@navbar-default-toggle-icon-bar-bg', '@navbar-default-toggle-border-color', '@navbar-inverse-color', '@navbar-inverse-bg', '@navbar-inverse-link-color', '@navbar-inverse-link-hover-color', '@navbar-inverse-link-hover-bg', '@navbar-inverse-link-active-color', '@navbar-inverse-link-active-bg', '@navbar-inverse-link-disabled-color', '@navbar-inverse-link-disabled-bg', '@navbar-inverse-brand-color', '@navbar-inverse-brand-hover-color', '@navbar-inverse-brand-hover-bg', '@navbar-inverse-toggle-hover-bg', '@navbar-inverse-toggle-icon-bar-bg', '@navbar-inverse-toggle-border-color', '@nav-link-hover-bg', '@nav-disabled-link-color', '@nav-disabled-link-hover-color', '@nav-open-link-hover-color', '@nav-open-caret-border-color', '@nav-pills-active-link-hover-color', '@nav-pills-active-link-hover-bg', '@nav-tabs-active-link-hover-color', '@nav-tabs-active-link-hover-bg', '@nav-tabs-active-link-hover-border-color', '@nav-tabs-justified-link-border-color', '@nav-tabs-justified-active-link-border-color', '@table-bg', '@table-bg-accent', '@table-bg-hover', '@table-border-color', '@input-color', '@input-bg', '@input-border', '@legend-color', '@legend-border-color', '@input-color', '@input-bg', '@input-border', '@input-bg-disabled', '@input-color-placeholder', '@legend-color', '@legend-border-color', '@input-group-addon-bg', '@input-group-addon-border-color', '@dropdown-bg', '@dropdown-border', '@dropdown-fallback-border', '@dropdown-caret-color', '@dropdown-divider-bg', '@dropdown-link-color', '@dropdown-link-hover-color', '@dropdown-link-hover-bg', '@dropdown-link-active-color', '@dropdown-link-active-bg', '@dropdown-link-disabled-color', '@panel-bg', '@panel-inner-border', '@panel-footer-bg', '@panel-default-text', '@panel-default-border', '@panel-default-heading-bg', '@panel-primary-text', '@panel-primary-border', '@panel-primary-heading-bg', '@panel-success-text', '@panel-success-border', '@panel-success-heading-bg', '@panel-info-text', '@panel-info-border', '@panel-info-heading-bg', '@panel-warning-text', '@panel-warning-border', '@panel-warning-heading-bg', '@panel-danger-text', '@panel-danger-border', '@panel-danger-heading-bg', '@well-bg', '@accordion-border-bg', '@badge-color', '@badge-bg', '@badge-link-hover-color', '@badge-active-color', '@badge-active-bg', '@breadcrumb-color', '@breadcrumb-bg', '@breadcrumb-active-color', '@jumbotron-bg', '@jumbotron-color', '@jumbotron-heading-color', '@modal-content-bg', '@modal-backdrop-bg', '@modal-backdrop-bg', '@modal-content-border-color', '@modal-header-border-color', '@modal-content-fallback-border-color', '@modal-backdrop-bg', '@modal-header-border-color', '@carousel-control-color', '@carousel-indicator-border-color', '@carousel-indicator-active-bg', '@carousel-caption-color', '@list-group-bg', '@list-group-hover-bg', '@list-group-active-bg', '@list-group-border', '@list-group-active-border', '@list-group-active-color', '@thumbnail-bg', '@thumbnail-caption-padding', '@thumbnail-border', '@progress-bg', '@progress-bar-warning-bg', '@progress-bar-color', '@progress-bar-bg', '@progress-bar-danger-bg', '@progress-bar-success-bg', '@progress-bar-info-bg', '@pagination-bg', '@pagination-active-color', '@pagination-border', '@pagination-disabled-color', '@pagination-active-bg', '@pager-disabled-color', '@label-default-bg', '@label-primary-bg', '@label-success-bg', '@label-info-bg', '@label-warning-bg', '@label-danger-bg', '@tooltip-color', '@tooltip-bg', '@tooltip-arrow-color', '@popover-bg', '@popover-title-bg', '@popover-arrow-outer-fallback-color', '@popover-arrow-color', '@popover-arrow-outer-color', '@popover-border-color', '@popover-fallback-border-color', '@close-color', '@text-muted', '@headings-small-color', '@blockquote-border-color', '@abbr-border-color', '@blockquote-small-color', '@page-header-border-color', '@hr-border', '@gray-darker', '@gray-dark', '@gray-light', '@gray-lighter', '@ddd', '@fff'],
			grays : {
				'@black':                 '#000',
				'@grayDarker':            '#222',
				'@grayDark':              '#333',
				'@gray':                  '#555',
				'@grayLight':             '#999',
				'@grayLighter':           '#eee',
				'@white':                 '#fff',
				'@gray-darker':           '#222',
				'@gray-dark':             '#333',
				'@gray-light':            '#999',
				'@gray-lighter':          '#eee',
				'@ddd':                   '#ddd',
				'@fff':                   '#fff',
			}
		},
		placeholders = $('input[placeholder],input[data-var]');

	$.fn.colorBootsrap = function() {

		this.each(function() {
			// check input field for a value, otherwise use the placeholder value
			var color = $(this).val().length > 0 ? $(this).val() : $(this).attr('placeholder').length > 0 ? $(this).attr('placeholder') : $(this).attr('data-var'),
				i = COLORS.lessColors.indexOf(color),
				lessColor,
				label,
				labelText;
			// if the color value is a less color variable, set the color value to use that variable's value
			if(i >= 0) {
				lessColor = color;

				// gray variables are not customizable so set them to the LESS value
				if(COLORS.grays[color]) {
					color = COLORS.grays[color];
				}
				else {
					color = $('label:contains('+COLORS.lessColors[i]+')').css('color');
				}
			}

			// test if the color value look a like a legal color
			if(COLORS.legalColors.test(color)){
				// update the label for this field to use the color value as its color
				label = $(this).prev('label');
				labelText = label.text();
				$(label).css('color',color);
				// if this is a LESS color variable field, update all the fields that reference this variable
				if(COLORS.lessColors.indexOf(labelText) >= 0) {
					$(placeholders).each(function() {
						var val = $(this).val(),
							changeColor = val && val === labelText || !val && $(this).attr('placeholder') === labelText|| !val && $(this).attr('data-var') === labelText  ? true : false;
						if(changeColor) {
							$(this).prev('label').css('color',color);
						}
					});
				}
			}
		});
		return this;
	};
})(jQuery);
